language: node_js
node_js:
    - 10
    - 12
branches:
    only:
        - master
cache:
    directories:
        - node_modules
install:
    - travis_retry npm install
script:
    - npm run build
    - npm run test
    - npm run doc
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: docs
    on:
        branch: master
jobs:
    include:
        - stage: release
          node_js: lts/*
          script:
              - npm run semantic-release
notifications:
    email: false
