language: node_js
node_js:
    - 8
    - 10
    - 12
branches:
    only:
        - master
cache:
    directories:
        - node_modules
install:
    - travis_retry npm install
script:
    - npm run test
    - npm run build
jobs:
    include:
        - stage: release
          node_js: lts/*
          script:
              - npm run semantic-release
notifications:
    email: false
